#!/bin/bash

set -e


# . .env
cat <<EOF
DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS

POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_HOST=$POSTGRES_HOST
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_NAME=$POSTGRES_NAME
POSTGRES_DB=$POSTGRES_DB

DJANGO_ADMIN_USER=$DJANGO_ADMIN_USER
DJANGO_ADMIN_PASSWORD=$DJANGO_ADMIN_PASSWORD

AWS_ECR_REPO_DJANGO=$AWS_ECR_REPO_DJANGO
AWS_ECR_REPO_NGINX=$AWS_ECR_REPO_NGINX
AWS_ECR_REPO_POSTGRES=$AWS_ECR_REPO_POSTGRES

export TF_VAR_MAIN_SAVING=$TF_VAR_MAIN_SAVING
export TF_VAR_STAGING_SAVING=$TF_VAR_STAGING_SAVING
export TF_VAR_DEVELOP_SAVING=$TF_VAR_DEVELOP_SAVING

REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN
CIRCLE_BRANCH=$CIRCLE_BRANCH

EOF